version: "3.8"

services:
  db:
    restart: always
    image: postgres:14
    container_name: pgsql_bet_provider
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - /var/log/postgresql:/logs
    networks:
      - default
    env_file:
      - .env
  line_provider:
    build: ./line_provider/
    restart: always
    container_name: line_provider
    ports:
      - "0.0.0.0:8010:8000"
    env_file:
      - .env
    volumes:
      - ./line_provider/:/app
    depends_on:
      - db
    networks:
      - default
  broker:
    container_name: message_broker
    image: "rabbitmq:3.9-management-alpine"
    ports:
      - "8080:15672"
      - "5672:5672"
    hostname: fastapi_broker
    networks:
      - default
  bet_maker:
    build: ./bet_maker/
    restart: always
    container_name: bet_maker
    ports:
      - "0.0.0.0:8012:8000"
    env_file:
      - .env
    volumes:
      - ./bet_maker/:/app
    depends_on:
      - db
      - line_provider
    networks:
      - default

networks:
  default:
    external: true
    name: docker-network